name: Gtihub-Action-IPTIME-WOL

#on : [push]
on:
    push:
        branches: [test]
    pull_request:
        branches: [test]
    schedule:
        - cron: "0 0 * * *"

jobs:
    WOL:
        name: "WOL"
        runs-on: ubuntu-latest
        steps:
            - id : getCurrentTime
              name : "get Current Time"
              run : |1
                  sudo ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
                  time=$(date '+%Y년 %m월 %d일 %H:%M:%S')
                  echo "set-output name=now::${time}"
                  echo "set-output name=title::${time} 실행결과입니다."

            - id : sendMagicPacket
              name : "send Magic Packet"
              run : |
                  RES_CODE=$(curl -o /dev/null -H "Authorization: Basic ${{secrets.IPTIME_BASIC}}" -w "%{http_code}" "${{secrets.IPTIME_DOMAIN}}/cgi-bin/wol_apply.cgi?act=wakeup&mac=${{secrets.IPTIME_MAC}}")
                  if [ ${RES_CODE} == "200" ]; then
                      echo "set-output name=status::성공"
                  else
                      echo "set-output name=status::실패"
                  fi

            - id : createIssue
              name : "Create Issue"
              run : |
                  title=${{ steps.getCurrentTime.outputs.title }}
                  labels=${{github.event_name}}
                  body=${{ steps.sendMagicPacket.outputs.status }}
                  RES_CODE=$(curl -o /dev/null -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/{github.repository}/issues -d '{"title": ${title}, "labels" : ${labels}}')
                  echo $RES_CODE