name: Gtihub-Action-IPTIME-WOL

#on : [push]
on:
    push:
        branches: [test]
    pull_request:
        branches: [test]
    schedule:
        - cron: "0 0 * * *"

jobs:
    WOL:
        name: "WOL"
        runs-on: ubuntu-latest
        steps:
            - id : getCurrentTime
              name : "get Current Time"
              run : |1
                  sudo ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
                  time=$(date '+%Y년 %m월 %d일 %H:%M:%S')
                  echo "now=${time}" >> $GITHUB_ENV
                  echo "title=${time} 실행결과입니다." >> $GITHUB_ENV

            - id : sendMagicPacket
              name : "send Magic Packet"
              run : |
                  RES_CODE=$(curl -H "Authorization: Basic ${{secrets.IPTIME_BASIC}}" -w "%{http_code}" "${{secrets.IPTIME_DOMAIN}}/cgi-bin/wol_apply.cgi?act=wakeup&mac=${{secrets.IPTIME_MAC}}")
                  status="실패"
                  if [ ${RES_CODE} == "200" ]; then
                      status="실패"
                  fi
                  echo "status=${status}" >> $GITHUB_ENV

            - id : createIssue
              name : "Create Issue"
              run : |
                  labels=${{github.event_name}}
                  repository=${{github.repository}}
                  body=$status
                  api="https://api.github.com/repos/$repository/issues"
                  contents='{"title": $title, "labels" : $labels, "body" : $body}'
                  RES_CODE=$(curl -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" $api -d $contents)
                  echo $RES_CODE