name: Gtihub-Action-IPTIME-WOL

#on : [push]
on:
    push:
        branches: [test]
    pull_request:
        branches: [test]
    schedule:
        # 00*** 에 스케줄하였지만 실행은 30분 뒤에 되는 결과가 나와 30분 앞 당겼음
        - cron: "30 23 * * *"

jobs:
    getCurrentTime:
        name: "Get current time"
        runs-on: ubuntu-latest
        steps:
            - run : |
                  sudo ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
                  time=$(date '+%Y년 %m월 %d일 %H:%M:%S')
                  echo "set-output name=now::" + $time

    sendMagicPacket:
        name: "send curl"
        needs: getCurrentTime
        runs-on: ubuntu-latest
        steps:
            - run : |
                  RES_CODE=$(curl -o /dev/null -H "Authorization: Basic ${{secrets.IPTIME_BASIC}}" -w "%{http_code}" "${{secrets.IPTIME_DOMAIN}}/cgi-bin/wol_apply.cgi?act=wakeup&mac=${{secrets.IPTIME_MAC}}")
                  echo $RES_CODE

    createIssue:
      name: "Create Issue"
      needs: [sendMagicPacket, getCurrentTime]
      runs-on: ubuntu-latest
      steps:
        - uses: nashmaniac/create-issue-action@v1.1
          with:
            title: ${{ needs.getCurrentTime.outputs.now }} 실행결과입니다.
            token: ${{secrets.GITHUB_TOKEN}}
            assignees: ${{github.actor}}
            labels: result
            body: ${{ needs.sendMagicPacket.outputs.status }}